#!/usr/bin/python3

import sys
import os

KEYWORD = '_PLEASE_REPLACE_BY_FILE_CONTENTS:'

MARKDOWN_COMMENT = [
'',
'[//]: # (This code is automatically generated by replace-by-file-contents.py script)',
'[//]: # (located in cmake folder.)',
'[//]: # (Do not change it manually, but rather change Markdown code)',
'[//]: # (in appropriate *.md.in file)',
''
]


source_path = os.path.dirname(sys.argv[1])

with open(sys.argv[1], 'r') as input_file:
    with open(sys.argv[2], 'w') as output_file:
        for line in MARKDOWN_COMMENT:
            output_file.write(line + '\n')
        for line in input_file:
            if line.lstrip()[:len(KEYWORD)] == KEYWORD:
                with open(os.path.join(source_path, line[len(KEYWORD):].rstrip()), 'r') as contents_file:
                    contents = contents_file.read()
                    output_file.write(contents + '\n')
            else:
                output_file.write(line)